module.exports.user_Service = require("./user.service")
module.exports.cart_Service = require("./cart.service")
module.exports.product_Service = require("./product.service")
module.exports.category_Service = require("./category.service")
module.exports.sub_category_Service = require("./sub.category.service")
module.exports.sub_child_category_Service = require("./sub.child.category.service")